### ISSUE TITLE
Nick changes cause problem with bot.lastChannel

### ISSUE THREAD

**Issue by dabbers** [dabbers/DeBot.js#14]
Repro:
Change bot nick to something.
Change bot nick back

```
                    bot.lastChannel = (msg.To.Type == "Client" ? msg.From.Parts[0] : msg.To.Par
                                    ^
```

TypeError: Cannot set property 'lastChannel' of undefined
    at BotGroup.<anonymous> (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\Commandable.js:133:20)
    at BotGroup.emit (events.js:98:17)
    at Bot.<anonymous> (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\BotGroup.js:146:10)
    at Bot.emit (events.js:117:20)
    at Object.parse (C:\Users\me_000\Documents\Projects\DeBot.js\src\node_modules\dabbit.base\Parser.js:156:25)
    at Network.rawMessageReceived (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\Network.js:179:16)
    at DeBotConnection.RawMessageReceived (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\Network.js:164:18)
    at Connection.onRead (C:\Users\me_000\Documents\Projects\DeBot.js\src\node_modules\dabbit.base\Connection.js:133:14)
    at CleartextStream.NodeSocket.onData (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\NodeSocket.js:67:13)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:764:14)

**Comment by dabbers** [comment]
Hit repro again. Bot joined when nick was already in use, performed command and hit same error:
C:\Users\me_000\Documents\Projects\DeBot.js\src\core\Commandable.js:133
                        bot.lastChannel = (msg.To.Type == "Client" ? msg.From.Parts[0] : msg.To.Par
                                        ^
TypeError: Cannot set property 'lastChannel' of undefined
    at BotGroup.<anonymous> (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\Commandable.js:133:20)
    at BotGroup.emit (events.js:98:17)
    at Bot.<anonymous> (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\BotGroup.js:146:10)
    at Bot.emit (events.js:117:20)
    at Object.parse (C:\Users\me_000\Documents\Projects\DeBot.js\src\node_modules\dabbit.base\Parser.js:156:25)
    at Network.rawMessageReceived (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\Network.js:179:16)
    at DeBotConnection.RawMessageReceived (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\Network.js:164:18)
    at Connection.onRead (C:\Users\me_000\Documents\Projects\DeBot.js\src\node_modules\dabbit.base\Connection.js:133:14)
    at CleartextStream.NodeSocket.onData (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\NodeSocket.js:67:13)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:764:14)

**Comment by dabbers** [comment]
I think I may have fixed this.  The Network.js file had missing logic when the OnNickCHange event was fired. It updated its nick to anything. Will need to test later.
