### ISSUE TITLE
Group unloading module

### ISSUE THREAD

**Issue by dabbers** [dabbers/DeBot.js#16]
Attempted to unload then reload a group.module 

PROXYBOT  cleanupMethods
PROXYBOT  cleanupMethods

C:\Users\me_000\Documents\Projects\DeBot.js\src\core\FakeGroup.js:30
                                        callbacksToRemove.forEach(function(cb) { realBot.removeListener(cb.event,
                                                                                 ^
ReferenceError: realBot is not defined
    at C:\Users\me_000\Documents\Projects\DeBot.js\src\core\FakeGroup.js:30:47
    at Array.forEach (native)
    at BotGroup.<anonymous> (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\FakeGroup.js:30:24)
    at self.uninit (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\Module.js:36:15)
    at BotGroup.ModuleHandler.obj.unloadModule (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\ModuleHandler.js:33:25)
    at Object.eval (eval at <anonymous> (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\BotGroup.js:228:32), <anonymous
    at Object.callback (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\BotGroup.js:228:3)
    at BotGroup.<anonymous> (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\Commandable.js:136:23)
    at BotGroup.emit (events.js:98:17)
    at Bot.<anonymous> (C:\Users\me_000\Documents\Projects\DeBot.js\src\core\BotGroup.js:146:10)

**Comment by dabbers** [comment]
Fixed in 777fb63. Should be fine now.
